/**
 * Bakes the coastline and the town list straight into the renderer bundle.
 *
 * They used to be read from disk at runtime, which meant they silently vanished
 * whenever the packaging layout shifted. Embedding them removes the whole class
 * of bug: if the app runs at all, the map is there.
 */
const fs = require('fs');
const path = require('path');

const svg = fs.readFileSync('assets/uk-base.svg', 'utf8');
const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
const places = JSON.parse(fs.readFileSync('assets/places.json', 'utf8'));
const size = svg.match(/width="(\d+)"\s+height="(\d+)"/);
const [w, h] = size ? [Number(size[1]), Number(size[2])] : [16671, 19640];

fs.mkdirSync('src/generated', { recursive: true });
fs.writeFileSync(
  'src/generated/assets.ts',
  '// Generated by scripts/embed-assets.js — do not edit.\n' +
    `export const BASEMAP_SVG = ${JSON.stringify(inner)};\n` +
    `export const BASEMAP_W = ${w};\nexport const BASEMAP_H = ${h};\n` +
    `export const PLACES: { n: string; x: number; y: number; p: number; t: number }[] = ${JSON.stringify(places.places)};\n`,
);
console.log(`embedded basemap (${(inner.length / 1024).toFixed(0)} kB) and ${places.places.length} places`);
