/**
 * Bakes the coastline and the town list straight into the renderer bundle.
 *
 * They used to be read from disk at runtime, which meant they silently vanished
 * whenever the packaging layout shifted. Embedding them removes the whole class
 * of bug: if the app runs at all, the map is there.
 */
const fs = require('fs');
const path = require('path');

const outline = JSON.parse(fs.readFileSync('assets/outline.json', 'utf8'));
const places = JSON.parse(fs.readFileSync('assets/places.json', 'utf8'));
const projection = JSON.parse(fs.readFileSync('assets/projection.json', 'utf8'));
const xs = outline.shapes.flatMap((s) => s.ring.map((p) => p.x));
const ys = outline.shapes.flatMap((s) => s.ring.map((p) => p.y));
const pad = 3;
const w = (Math.max(...xs) - Math.min(...xs) + pad * 2) * outline.unit;
const h = (Math.max(...ys) - Math.min(...ys) + pad * 2) * outline.unit;

fs.mkdirSync('src/generated', { recursive: true });
fs.writeFileSync(
  'src/generated/assets.ts',
  '// Generated by scripts/embed-assets.js — do not edit.\n' +
    `import type { Outline } from '../core/outline';\n` +
    `export const OUTLINE: Outline = ${JSON.stringify(outline)};\n` +
    `export const BASEMAP_W = ${w};\nexport const BASEMAP_H = ${h};\n` +
    `export const PROJECTION = ${JSON.stringify(projection)} as {\n` +
    `  unit: number; scale: number; lat0: number; minx: number; miny: number;\n};\n` +
    `export const PLACES: { n: string; x: number; y: number; p: number; t: number }[] = ${JSON.stringify(places.places)};\n`,
);
console.log(
  `embedded outline (${outline.shapes.length} shapes, ` +
    `${outline.shapes.reduce((n, s) => n + s.ring.length, 0)} points) and ${places.places.length} places`,
);
